version: '3.8'

services:
  app:
    build: .
    ports:
      - "55359:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.docker
    depends_on:
      - keydb
    restart: always

  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: