version: '3.8'

services:
  app:
    build: .
    ports:
      - "55359:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.docker
    depends_on:
      - keydb
      - mysql
    restart: always

  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "65355:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: instaconectDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  redis_data:
  mysql_data:
